STOWDEST = /usr/local/stow/scponly

SUDO = sudo
SCPUSER = scp

.PHONY: centos-dep config build

scponly:
	git clone git://github.com/scponly/$@.git
config: scponly
	sh $^/configure --prefix=$(STOWDEST) \
		--enable-winscp-compat \
		--enable-scp-compat \
		--enable-rsync-compat \
		--with-sftp-server=/usr/libexec/openssh/sftp-server
post-install:
	STOWDEST=$(STOWDEST) bash install.bash
