

nerd-fonts:
	git submodule add git://github.com/ryanoasis/$@
update: nerd-fonts
	git submodule update --init

install:
	bash install.sh \
		3270 \
		DejaVuSansMono \
		FantasqueSansMono \
		Inconsolata \
		Monofur \
		RobotoMono \
		SourceCodePro \
		UbuntuMono
