
update: distclean
	git pull

fedora-dep:
	sudo dnf install -y atk-devel cairo-devel gpm-devel gtk3-devel libbonoboui-devel libX11-devel libXpm-devel libXt-devel ncurses-devel python-devel python3-devel

distclean:
	cd src && make distclean

config: distclean
	cd src && sh configure --prefix=/usr/local/stow/vim --disable-nls --with-features=huge \
		--enable-gui=gtk3 --disable-gtk2-check --enable-gpm \
		--enable-cscope --enable-pythoninterp --enable-python3interp 

