STOWDEST ?= /usr/local/stow/gimp-2.9


debian-dep:
	sudo apt-get install -y libjson-c-dev # scons

fedora-dep:
	sudo dnf install -y json-c-devel # scons


SRC:
	git submodule add git@github.com:mypaint/libmypaint.git $@
update: SRC
	git submodule update --init
config: update
	sh SRC/autogen.sh --prefix=$(STOWDEST)
	sh SRC/configure --prefix=$(STOWDEST)
