STOWDEST ?= /usr/local/stow/rtorrent

export ACLOCAL_FLAGS ?= -I /usr/local/share/aclocal
export PKG_CONFIG_PATH ?= /usr/local/lib/pkgconfig


fedora-dep:
	sudo dnf install -y cppunit-devel ncurses-devel libcurl-devel xmlrpc-c-devel pkgconfig


rtorrent:
	git submodule add git://github.com/rakshasa/$@.git
config: rtorrent
	cd $^ && sh autogen.sh --prefix=$(STOWDEST)
	sh $^/configure --prefix=$(STOWDEST) \
		--enable-ipv6 --with-xmlrpc-c
