
fedora-dep:
	sudo dnf install -y gdk-pixbuf2-devel startup-notification-devel \
		perl-ExtUtils-Embed perl-ExtUtils-CBuilder perl-ExtUtils-ParseXS

config:
	###sh autogen.sh
	sh configure -C --prefix=/usr/local/stow/rxvt-unicode \
		--enable-256-color \
		--enable-smart-resize

my-patch: fedora.patch
	patch -b -p1 < $@
