STOWDEST ?= /usr/local/stow/openssl-1.0.2


openssl:
	git submodule add git://github.com/openssl/$@.git
	cd $@ && git checkout OpenSSL_1_0_2-stable
config: openssl
	$^/config --prefix=$(STOWDEST) --openssldir=/etc/ssl \
		enable-ec_nistp_64_gcc_128
	$(MAKE) -C $^ depend
