
debian-dep:
	sudo apt-get install libdevmapper-dev uuid-dev \
		libgcrypt11-dev libudev-dev
build:
	mkdir $@
	cd $@ && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/stow/tc-play ..
	$(MAKE) -C $@
install: build
	$(MAKE) -C build install
