STOWDEST ?= /usr/local/stow/tc-play


debian-dep:
	sudo apt-get install libdevmapper-dev uuid-dev \
		libgcrypt11-dev libudev-dev


tc-play:
	git submodule add git://github.com/bwalex/tc-play.git
update: tc-play
	git submodule update --init

build: tc-play
	- mkdir $@
	cd $@ && cmake -DCMAKE_INSTALL_PREFIX:PATH=$(STOWDEST) ../$^
	$(MULTIMAKE) -C $@
install: build
	$(MULTIMAKE) -C $^ $@
