STOWDEST ?= /usr/local/stow/st


debian-dep:
	sudo apt-get install libxft-dev


st:
	git submodule add git://git.suckless.org/$@
update: st
	git submodule update --init
config: st
	patch < patches/font.patch
	patch < patches/paths.patch
post-install:
	cp -Rb misc/* $(STOWDEST)
