
update:
	git pull

centos-dep:
	sudo yum group install "Development Tools"
	sudo yum install -y openssl-devel

config:
	sh autogen.sh --prefix=/usr/local/stow/tor
	sh configure --prefix=/usr/local/stow/tor \
		--disable-samples --enable-gcc-hardening --enable-openssl
