
STOWDEST ?= /usr/local/stow/tor


centos-dep:
	sudo yum group install "Development Tools"
	#sudo yum install -y openssl-devel

libevent:
	git submodule add git://github.com/libevent/$@.git
update: libevent
	git submodule update --init
config: libevent
	cd $^ && sh autogen.sh --prefix=$(STOWDEST)
	sh $^/configure --prefix=$(STOWDEST) \
		--disable-samples --enable-gcc-hardening --enable-openssl
