
update:
	git pull

debian-dep:
	sudo apt-get install -y autoconf libtool
fedora-dep:
	sudo dnf install -y autoconf libtool
	
config:
	sh autogen.sh --prefix=/usr/local/stow/gimp-2.9
	sh configure --prefix=/usr/local/stow/gimp-2.9 --disable-docs
