STOWDEST ?= /usr/local/stow/gimp-2.9

babl:
	git submodule add git://git.gnome.org/$@
update: babl
	git submodule update --init

debian-dep:
	sudo apt-get install -y autoconf libtool
fedora-dep:
	sudo dnf install -y autoconf libtool

config: babl
	cd babl && sh autogen.sh --prefix=$(STOWDEST)
	sh babl/configure --prefix=$(STOWDEST) \
		--disable-docs
