STOWDEST ?= /usr/local/stow/gimp-2.9

src:
	git submodule add git://git.gnome.org/babl src
update: src
	git submodule update --init

debian-dep:
	sudo apt-get install -y autoconf libtool
fedora-dep:
	sudo dnf install -y autoconf libtool

config: update
	sh src/autogen.sh --prefix=$(STOWDEST)
	sh src/configure --prefix=$(STOWDEST) \
		--disable-docs
