STOWDEST ?= /usr/local/stow/rtorrent


fedora-dep:
	sudo dnf install -y cppunit-devel openssl-devel zlib-devel pkgconfig


libtorrent:
	git submodule add git://github.com/rakshasa/$@.git
update: libtorrent
	git submodule update --init
config: libtorrent
	cd $^ && sh autogen.sh --prefix=$(STOWDEST)
	$^/configure --prefix=$(STOWDEST)
