STOWDEST ?= /usr/local/stow/libressl

SUDO = sudo
.PHONY: centos-dep config build

centos-dep:
	$(SUDO) yum install -y cmake perl-podlators # ninja-build


SRC:
	git clone git://github.com/libressl-portable/portable.git $@
config: SRC
	cd $^ && sh autogen.sh --prefix=$(STOWDEST)
	sh $^/configure --prefix=$(STOWDEST) --sysconfdir=/etc \
		--enable-nc --with-openssldir=/etc/ssl
	$(MULTIMAKE) -C SRC check
#build:
#	[ -d $@ ] || mkdir $@
#	cd $@ && cmake -DCMAKE_INSTALL_PREFIX:PATH=$(STOWDEST)/ ..
