
centos-dep:
	yum install -y cmake perl-podlators # ninja-build
my-config:
	sh autogen.sh --prefix=/usr/local/stow/libressl
	sh configure --prefix=/usr/local/stow/libressl --sysconfdir=/etc \
		--enable-nc --with-openssldir=/etc/ssl
build:
	mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/stow/libressl ..
	#cd build && make && make check
