

debian-dep:
	sudo apt-get install -y cmake mercurial yasm
fedora-dep:
	sudo dnf install -y cmake mercurial yasm
config:
	- mkdir -p build/linux
	cd build/linux && cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr/local/stow/ffmpeg ../../source

install:
	$(MAKE) -C build/linux install
