STOWDEST ?= /usr/local/stow/ffmpeg


debian-dep:
	sudo apt-get install -y cmake mercurial yasm
fedora-dep:
	sudo dnf install -y cmake mercurial yasm


x265:
	hg clone https://bitbucket.org/multicoreware/$@
build:
	- mkdir $@
	cd $@ && cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$(STOWDEST) ../source
install:
	$(MAKE) -C build $@
