STOWDEST ?= /usr/local/stow/ffmpeg

CFLAGS += -I/usr/local/include


debian-dep:
	sudo apt-get install -y yasm
fedora-dep:
	sudo dnf install -y yasm


x264:
	git submodule add git://git.videolan.org/$@
update: x264
	git submodule update --init
config: x264
	sh $^/configure --prefix=$(STOWDEST) \
		--enable-shared --enable-pic
	
