CFLAGS += -I/usr/local/include

debian-dep:
	sudo apt-get install -y yasm
fedora-dep:
	sudo dnf install -y yasm
config:
	- mkdir my-build
	cd my-build && bash ../configure --prefix=/usr/local/stow/ffmpeg --enable-shared --enable-pic
	
