

fdk-aac:
	git submodule add git://git.code.sf.net/p/opencore-amr/$@
update: fdk-aac
	git submodule update --init

debian-dep:
	sudo apt-get -y install autoconf libtool pkg-config

config: update
	cd fdk-aac && autoreconf -fiv
	sh fdk-aac/configure --prefix=/usr/local/stow/ffmpeg
