CFLAGS=-fpic

debian-dep:
	sudo apt-get install -y yasm
fedora-dep:
	sudo dnf install -y yasm
config:
	./configure --prefix=/usr/local/stow/ffmpeg --disable-examples --disable-docs \
		--enable-vp9-postproc --disable-vp10 --as=yasm \
		--enable-runtime-cpu-detect --enable-shared --enable-postproc-visualizer \
		--enable-multi-res-encoding --enable-vp9-temporal-denoising --enable-webm-io
